AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM project for rikitraki back end Lambdas

Resources:
  rikitrakiapi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowMethods: [GET, POST, PUT, DELETE, OPTIONS]
        AllowHeaders: [Content-Type, Authorization]
        AllowOrigins: ["*"]

  AllowS3PutAllPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allow Lambda functions to put objects in rikitraki bucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: arn:aws:s3:::rikitraki/*

  AllowS3DeleteAllPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allow Lambda functions to delete objects in rikitraki bucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:DeleteObject
            Resource: arn:aws:s3:::rikitraki/*

  getTracksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTracks
      Handler: tracks/getTracks.handler
      Runtime: nodejs22.x
      CodeUri: functions/
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks
            Method: get
            ApiId: !Ref rikitrakiapi

  getNumberOfTracksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getNumberOfTracks
      Handler: tracks/getNumberOfTracks.handler
      Runtime: nodejs22.x
      CodeUri: functions/
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/number
            Method: get
            ApiId: !Ref rikitrakiapi

  getTrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTrack
      Handler: tracks/getTrack.handler
      Runtime: nodejs22.x
      CodeUri: functions/
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}
            Method: get
            ApiId: !Ref rikitrakiapi

  getMotdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getMotd
      CodeUri: functions/
      Handler: tracks/getMotd.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /motd
            Method: get
            ApiId: !Ref rikitrakiapi

  getThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getThumbnail
      CodeUri: functions/
      Handler: tracks/getThumbnail.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: rikitraki
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/thumbnail/{picIndex}
            Method: get
            ApiId: !Ref rikitrakiapi

  getPictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getPicture
      CodeUri: functions/
      Handler: tracks/getPicture.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: rikitraki
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/picture/{picIndex}
            Method: get
            ApiId: !Ref rikitrakiapi

  getTrackGPXFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTrackGPX
      CodeUri: functions/
      Handler: tracks/getTrackGPX.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: rikitraki
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/GPX
            Method: get
            ApiId: !Ref rikitrakiapi

  getTrackGeotagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTrackGeotags
      CodeUri: functions/
      Handler: tracks/getTrackGeotags.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          BUCKET_NAME: rikitraki
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/geotags
            Method: get
            ApiId: !Ref rikitrakiapi

  getTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getToken
      CodeUri: functions/
      Handler: users/getToken.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /token
            Method: get
            ApiId: !Ref rikitrakiapi

  getUserInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getUserInfo
      CodeUri: functions/
      Handler: users/getUserInfo.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/me
            Method: get
            ApiId: !Ref rikitrakiapi

  updateUserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateUserProfile
      CodeUri: functions/
      Handler: users/updateUserProfile.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/me
            Method: put
            ApiId: !Ref rikitrakiapi

  getResetTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getResetToken
      CodeUri: functions/
      Handler: users/getResetToken.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/MAILGUN_API_KEY}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /resettoken
            Method: get
            ApiId: !Ref rikitrakiapi

  resetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resetPassword
      CodeUri: functions/
      Handler: users/resetPassword.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/{username}
            Method: put
            ApiId: !Ref rikitrakiapi

  createUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createUser
      CodeUri: functions/
      Handler: users/createUser.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
          MAILGUN_API_KEY: !Sub "{{resolve:ssm:/rikitrakiapi/MAILGUN_API_KEY}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users
            Method: post
            ApiId: !Ref rikitrakiapi

  activateAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: activateAccount
      CodeUri: functions/
      Handler: users/activateAccount.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/{username}/activation
            Method: put
            ApiId: !Ref rikitrakiapi

  createTrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createTrack
      CodeUri: functions/
      Handler: tracks/createTrack.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - !Ref AllowS3PutAllPolicy
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          BUCKET_NAME: rikitraki
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks
            Method: post
            ApiId: !Ref rikitrakiapi

  updateTrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateTrack
      CodeUri: functions/
      Handler: tracks/updateTrack.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - !Ref AllowS3PutAllPolicy
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          BUCKET_NAME: rikitraki
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}
            Method: put
            ApiId: !Ref rikitrakiapi

  addPictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: addPicture
      CodeUri: functions/
      Handler: tracks/addPicture.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - !Ref AllowS3PutAllPolicy
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          BUCKET_NAME: rikitraki
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/picture/{picIndex}
            Method: post
            ApiId: !Ref rikitrakiapi

  deletePictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deletePicture
      CodeUri: functions/
      Handler: tracks/deletePicture.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - !Ref AllowS3DeleteAllPolicy
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          BUCKET_NAME: rikitraki
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/picture/{picIndex}
            Method: delete
            ApiId: !Ref rikitrakiapi

Outputs:
  ApiGatewayBaseUrl:
    Description: "HTTP API base URL for Prod stage"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
