AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM project for rikitraki back end Lambdas

Resources:
  rikitrakiapi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes: 
       - "*/*"
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      CacheClusterEnabled: false

  getTracksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTracks
      Handler: getTracks.handler
      Runtime: nodejs22.x
      CodeUri: functions/
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tracks
            Method: get
            RestApiId: !Ref rikitrakiapi

  getNumberOfTracksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getNumberOfTracks
      Handler: getNumberOfTracks.handler
      Runtime: nodejs22.x
      CodeUri: functions/
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tracks/number
            Method: get
            RestApiId: !Ref rikitrakiapi

  getTrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTrack
      Handler: getTrack.handler
      Runtime: nodejs22.x
      CodeUri: functions/
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tracks/{trackId}
            Method: get
            RestApiId: !Ref rikitrakiapi

  getMotdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getMotd
      CodeUri: functions/
      Handler: getMotd.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /motd
            Method: get
            RestApiId: !Ref rikitrakiapi

  getThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getThumbnail
      CodeUri: functions/
      Handler: getThumbnail.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: rikitraki
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tracks/{trackId}/thumbnail/{picIndex}
            Method: get
            RestApiId: !Ref rikitrakiapi

  getTrackGeotagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTrackGeotags
      CodeUri: functions/
      Handler: getTrackGeotags.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          BUCKET_NAME: rikitraki
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tracks/{trackId}/geotags
            Method: get
            RestApiId: !Ref rikitrakiapi

Outputs:
  ApiGatewayBaseUrl:
    Description: "API Gateway base URL for Prod stage"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  getTracksEndpoint:
    Description: "Full endpoint for getTracks Lambda"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tracks"

  getMotdEndpoint:
    Description: "Full endpoint for getMotd Lambda"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod/motd"

  getThumbnailEndpoint:
    Description: "Full endpoint for getMotd Lambda"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tracks/{trackId}/thumbnail/{picIndex}"

