AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM project for rikitraki back end Lambdas

Globals:
  Function:
    Runtime: nodejs22.x
    CodeUri: functions/
    MemorySize: 1024
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: rikitrakidyn
        BUCKET_NAME: rikitraki
    Tags:
      Project: rikitraki

Resources:
  rikitrakiapi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowMethods: [GET, POST, PUT, DELETE, OPTIONS]
        AllowHeaders: [Content-Type, Authorization]
        AllowOrigins: ["*"]

  AllowS3PutAllPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allow Lambda functions to put objects in rikitraki bucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: [s3:PutObject]
            Resource: arn:aws:s3:::rikitraki/*

  AllowS3DeleteAllPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allow Lambda functions to delete objects in rikitraki bucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: [s3:DeleteObject]
            Resource: arn:aws:s3:::rikitraki/*

  getTracksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTracks
      Handler: tracks/getTracks.handler
      Description: "Returns all tracks"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks
            Method: get
            ApiId: !Ref rikitrakiapi

  getNumberOfTracksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getNumberOfTracks
      Handler: tracks/getNumberOfTracks.handler
      Description: "Returns the number of tracks"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/number
            Method: get
            ApiId: !Ref rikitrakiapi

  getTrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTrack
      Handler: tracks/getTrack.handler
      Description: "Returns a single track"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}
            Method: get
            ApiId: !Ref rikitrakiapi

  getMotdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getMotd
      Handler: tracks/getMotd.handler
      Description: "Returns message of the day"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /motd
            Method: get
            ApiId: !Ref rikitrakiapi

  getThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getThumbnail
      Handler: tracks/getThumbnail.handler
      Description: "Returns thumbnail image"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/thumbnail/{picIndex}
            Method: get
            ApiId: !Ref rikitrakiapi

  getPictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getPicture
      Handler: tracks/getPicture.handler
      Description: "Returns full picture"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/picture/{picIndex}
            Method: get
            ApiId: !Ref rikitrakiapi

  getTrackGPXFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTrackGPX
      Handler: tracks/getTrackGPX.handler
      Description: "Returns GPX file"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/GPX
            Method: get
            ApiId: !Ref rikitrakiapi

  getTrackGeotagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTrackGeotags
      Handler: tracks/getTrackGeotags.handler
      Description: "Returns geotags for a track"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
        - AmazonS3ReadOnlyAccess
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/geotags
            Method: get
            ApiId: !Ref rikitrakiapi

  getTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getToken
      Handler: users/getToken.handler
      Description: "Issues JWT token"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /token
            Method: get
            ApiId: !Ref rikitrakiapi

  getUserInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getUserInfo
      Handler: users/getUserInfo.handler
      Description: "Returns user info"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/me
            Method: get
            ApiId: !Ref rikitrakiapi

  updateUserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateUserProfile
      Handler: users/updateUserProfile.handler
      Description: "Updates user profile"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/me
            Method: put
            ApiId: !Ref rikitrakiapi

  getResetTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getResetToken
      Handler: users/getResetToken.handler
      Description: "Issues reset token"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/MAILGUN_API_KEY}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /resettoken
            Method: get
            ApiId: !Ref rikitrakiapi

  resetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resetPassword
      Handler: users/resetPassword.handler
      Description: "Resets user password"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/{username}
            Method: put
            ApiId: !Ref rikitrakiapi

  createUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createUser
      Handler: users/createUser.handler
      Description: "Creates a new user"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
          MAILGUN_API_KEY: !Sub "{{resolve:ssm:/rikitrakiapi/MAILGUN_API_KEY}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users
            Method: post
            ApiId: !Ref rikitrakiapi

  activateAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: activateAccount
      Handler: users/activateAccount.handler
      Description: "Activates user account"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users/{username}/activation
            Method: put
            ApiId: !Ref rikitrakiapi

  createTrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createTrack
      Handler: tracks/createTrack.handler
      Description: "Creates a new track and uploads initial assets"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - !Ref AllowS3PutAllPolicy
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks
            Method: post
            ApiId: !Ref rikitrakiapi

  updateTrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateTrack
      Handler: tracks/updateTrack.handler
      Description: "Updates track metadata and assets"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - !Ref AllowS3PutAllPolicy
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}
            Method: put
            ApiId: !Ref rikitrakiapi

  addPictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: addPicture
      Handler: tracks/addPicture.handler
      Description: "Adds a picture to a track"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
        - !Ref AllowS3PutAllPolicy
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/picture/{picIndex}
            Method: post
            ApiId: !Ref rikitrakiapi

  deletePictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deletePicture
      Handler: tracks/deletePicture.handler
      Description: "Deletes a picture from a track"
      Policies:
        - AWSLambdaBasicExecutionRole
        - !Ref AllowS3DeleteAllPolicy
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}/picture/{picIndex}
            Method: delete
            ApiId: !Ref rikitrakiapi

  deleteTrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteTrack
      Handler: tracks/deleteTrack.handler
      Description: "Deletes a track and related assets"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonS3ReadOnlyAccess
        - !Ref AllowS3DeleteAllPolicy
      Environment:
        Variables:
          JWT_ISSUER: "rikitraki.com"
          JWT_SECRET: !Sub "{{resolve:ssm:/rikitrakiapi/JWT_SECRET}}"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /tracks/{trackId}
            Method: delete
            ApiId: !Ref rikitrakiapi

Outputs:
  ApiGatewayBaseUrl:
    Description: "HTTP API base URL for Prod stage"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
