AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Manual SAM project with getTracks Lambda

Resources:
  rikitrakiapi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes: 
       - "*/*"
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      CacheClusterEnabled: false

  getTracksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTracks
      Handler: getTracks.handler
      Runtime: nodejs22.x
      CodeUri: functions/
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tracks
            Method: get
            RestApiId: !Ref rikitrakiapi

  getMotdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getMotd
      CodeUri: functions/
      Handler: getMotd.handler
      Runtime: nodejs22.x
      MemorySize: 256
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: rikitrakidyn
          INDEX_NAME: TracksByDate
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /motd
            Method: get
            RestApiId: !Ref rikitrakiapi

  getThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getThumbnail
      CodeUri: functions/
      Handler: getThumbnail.handler
      Runtime: nodejs22.x
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          BUCKET_NAME: rikitraki
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tracks/{trackId}/thumbnail/{picIndex}
            Method: get
            RestApiId: !Ref rikitrakiapi

Outputs:
  ApiGatewayBaseUrl:
    Description: "API Gateway base URL for Prod stage"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  getTracksEndpoint:
    Description: "Full endpoint for getTracks Lambda"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tracks"

  getMotdEndpoint:
    Description: "Full endpoint for getMotd Lambda"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod/motd"

  getThumbnailEndpoint:
    Description: "Full endpoint for getMotd Lambda"
    Value: !Sub "https://${rikitrakiapi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tracks/{trackId}/thumbnail/{picIndex}"

